[package]
name = "era-web-tauri"
version = "0.3.0-tauri"
edition.workspace = true
license.workspace = true

[features]
webdriver = ["dep:tauri-plugin-wdio", "dep:tauri-plugin-wdio-webdriver"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
blake3.workspace = true
era-protocol.workspace = true
era-debug-protocol.workspace = true
era-runtime.workspace = true
era-runtime-protocol.workspace = true
era-web-bridge = { path = "../crates/era-web-bridge" }
encoding_rs = "0.8.35"
fontdb = "0.22.0"
glob = "0.3.3"
mimalloc = "0.1.52"
schemars = "=1.2.1"
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.1", features = [] }
tauri-plugin-dialog = "2.4.0"
tauri-plugin-wdio = { version = "1", optional = true }
tauri-plugin-wdio-webdriver = { version = "1", optional = true }
tempfile = "3.20.0"
unicode-normalization = "0.1.24"
walkdir = "2.5.0"

[lints]
workspace = true

[dev-dependencies]
minicbor.workspace = true
