[package]
name = "era-web-wasm"
version = "0.1.0-alpha.1-wasm"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
era-debug-protocol.workspace = true
era-runtime.workspace = true
era-runtime-protocol.workspace = true
era-web-bridge = { path = "../era-web-bridge" }
js-sys = "0.3.81"
serde.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.104"

[lints]
workspace = true
