[package]
name = "era-web-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
era-debug-protocol = { path = "../../../../crates/era-debug-protocol" }
era-runtime = { path = "../../../../crates/era-runtime" }
era-runtime-protocol = { path = "../../../../crates/era-runtime-protocol" }
era-web-bridge = { path = "../../../../crates/era-web-bridge" }
js-sys = "0.3.81"
serde.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.104"

[lints]
workspace = true
