type RuntimeStoreProjectionExtras = {
  bridgeKind: "tauri" | "browser";
  directProjectDirectoryAccess: boolean;
  memoryConstrained: boolean;
  testRuntimeEvidence(messageTypes?: string[]): Record<string, unknown>;
  testRuntimeEvidenceSummary(): Record<string, unknown>;
  testBackgroundWorkRevision(): number;
};

function projectRuntimeStore(context: Record<string, any>) {
  return {
    bridgeKind: context.bridge.kind,
    directProjectDirectoryAccess: context.bridge.directProjectDirectoryAccess === true,
    memoryConstrained: context.bridge.memoryConstrained === true,
    presentation: context.presentation,
    preferences: context.preferences,
    projectPreferences: context.projectPreferences,
    configurationEntries: context.configurationEntries,
    projectSource: context.projectSource,
    configurationReadOnly: context.configurationReadOnly,
    configurationSessionOnly: context.configurationSessionOnly,
    configurationRestartPending: context.configurationRestartPending,
    viewportMeasurement: context.viewportMeasurement,
    menuMode: context.menuMode,
    useMouse: context.useMouse,
    replaceFullWidthSpaces: context.replaceFullWidthSpaces,
    scrollHeight: context.scrollHeight,
    effectivePreferences: context.effectivePreferences,
    gameTextStyle: context.gameTextStyle,
    gameLineHeightPx: context.gameLineHeightPx,
    systemFonts: context.systemFonts,
    availableFontFamilies: context.availableFontFamilies,
    fontAccessStatus: context.fontAccessStatus,
    fontAccessError: context.fontAccessError,
    phase: context.phase,
    runtimeEpoch: context.runtimeEpoch,
    projectResourceGeneration: context.projectResourceGeneration,
    status: context.status,
    projectOpen: context.projectOpen,
    gameInformation: context.gameInformation,
    coreVersion: context.coreVersion,
    projectLoading: context.projectLoading,
    startupTelemetry: context.startupTelemetry,
    projectLoadProgressLabel: context.projectLoadProgressLabel,
    projectLoadProgressValue: context.projectLoadProgressValue,
    openProjectConfirmationOpen: context.openProjectConfirmationOpen,
    gameProgressLossConfirmation: context.gameProgressLossConfirmation,
    projectReloadDialogMode: context.projectReloadDialogMode,
    projectReloadTargetOptions: context.projectReloadTargetOptions,
    projectReloadDialogBusy: context.projectReloadDialogBusy,
    projectReloadDialogError: context.projectReloadDialogError,
    prompt: context.prompt,
    inputUndo: context.inputUndo,
    fault: context.fault,
    faultMessage: context.faultMessage,
    faultActionBusy: context.faultActionBusy,
    logs: context.logs,
    projectSettingsOpen: context.projectSettingsOpen,
    preferencesOpen: context.preferencesOpen,
    projectPreferencesWritable: context.projectPreferencesWritable,
    settingsBusy: context.settingsBusy,
    projectSettingsError: context.projectSettingsError,
    preferencesError: context.preferencesError,
    logsOpen: context.logsOpen,
    debugConsoleOpen: context.debugConsoleOpen,
    variablesOpen: context.variablesOpen,
    stackOpen: context.stackOpen,
    debugEnabled: context.debugEnabled,
    singleStepEnabled: context.singleStepEnabled,
    debugStop: context.debugStop,
    debugOutput: context.debugOutput,
    debugVariables: context.debugVariables,
    debugVariablesLoading: context.debugVariablesLoading,
    debugFibers: context.debugFibers,
    debugFrames: context.debugFrames,
    debugVariableValues: context.debugVariableValues,
    diagnosisExporting: context.diagnosisExporting,
    diagnosisProgress: context.diagnosisProgress,
    diagnosisProgressLabel: context.diagnosisProgressLabel,
    diagnosisProgressValue: context.diagnosisProgressValue,
    diagnosisResult: context.diagnosisResult,
    projectFileExporting: context.projectFileExporting,
    projectFileExportProgressLabel: context.projectFileExportProgressLabel,
    projectFileExportProgressValue: context.projectFileExportProgressValue,
    logNotifications: context.logNotifications,
    traditionalSaveDialogMode: context.traditionalSaveDialogMode,
    traditionalSaveSlots: context.traditionalSaveSlots,
    traditionalSaveImportName: context.traditionalSaveImportName,
    traditionalSaveTransferBusy: context.traditionalSaveTransferBusy,
    traditionalSaveTransferError: context.traditionalSaveTransferError,
    traditionalSaveOverwriteSlot: context.traditionalSaveOverwriteSlot,
    runtimeReady: context.runtimeReady,
    canExportDiagnosis: context.canExportDiagnosis,
    fullProjectExportSupported: context.fullProjectExportSupported,
    canExportProjectFile: context.canExportProjectFile,
    canManageTraditionalSaves: context.canManageTraditionalSaves,
    gameInteractionsBlocked: context.gameInteractionsBlocked,
    canOpenProject: context.canOpenProject,
    canStepDebug: context.canStepDebug,
    canInteract: context.canInteract,
    interactionEnabled: context.interactionEnabled,
    promptPlaceholder: context.promptPlaceholder,
    openPreferencesFromUser: context.openPreferencesFromUser,
    openProjectSettingsFromUser: context.openProjectSettingsFromUser,
    requestSystemFonts: context.requestSystemFonts,
    initialize: context.initialize,
    teardown: context.teardown,
    openProject: context.openProject,
    openProjectFile: context.openProjectFile,
    cancelOpenProject: context.cancelOpenProject,
    confirmOpenProject: context.confirmOpenProject,
    submitText: context.submitText,
    activate: context.activate,
    skip: context.skip,
    continueFromViewport: context.continueFromViewport,
    undo: context.undo,
    restart: context.restart,
    returnToTitle: context.returnToTitle,
    requestRestart: context.requestRestart,
    requestReturnToTitle: context.requestReturnToTitle,
    cancelGameProgressLossAction: context.cancelGameProgressLossAction,
    confirmGameProgressLossAction: context.confirmGameProgressLossAction,
    openProjectReloadDialog: context.openProjectReloadDialog,
    closeProjectReloadDialog: context.closeProjectReloadDialog,
    confirmProjectReload: context.confirmProjectReload,
    reloadProject: context.reloadProject,
    dismissFault: context.dismissFault,
    recoverFromFault: context.recoverFromFault,
    exportDiagnosis: context.exportDiagnosis,
    dismissLogNotification: context.dismissLogNotification,
    exportSnapshot: context.exportSnapshot,
    exportInputReplay: context.exportInputReplay,
    exportProjectFile: context.exportProjectFile,
    cancelProjectFileExport: context.cancelProjectFileExport,
    exportTraditionalSaveForTest: context.exportTraditionalSaveForTest,
    restoreSnapshot: context.restoreSnapshot,
    openTraditionalSaveDialog: context.openTraditionalSaveDialog,
    closeTraditionalSaveDialog: context.closeTraditionalSaveDialog,
    pickTraditionalSaveImport: context.pickTraditionalSaveImport,
    confirmTraditionalSaveTransfer: context.confirmTraditionalSaveTransfer,
    cancelTraditionalSaveOverwrite: context.cancelTraditionalSaveOverwrite,
    confirmTraditionalSaveOverwrite: context.confirmTraditionalSaveOverwrite,
    enableDebug: context.enableDebug,
    debugCommand: context.debugCommand,
    inspectWatches: context.inspectWatches,
    inspectTypedWatches: context.inspectTypedWatches,
    testRuntimeEvidence: (messageTypes?: string[]) =>
      context.testEvidence.snapshot(
        context.runtimeSessionObservationGeneration,
        messageTypes ? new Set(messageTypes) : undefined,
      ),
    testRuntimeEvidenceSummary: () =>
      context.testEvidence.summary(context.runtimeSessionObservationGeneration),
    testBackgroundWorkRevision: () => context.runtimePump.backgroundWorkRevision,
    openDebugDialog: context.openDebugDialog,
    closeDebugDialog: context.closeDebugDialog,
    stepDebug: context.stepDebug,
    toggleSingleStep: context.toggleSingleStep,
    continueDebug: context.continueDebug,
    saveProjectSettings: context.saveProjectSettings,
    saveClientPreferences: context.saveClientPreferences,
    shutdown: context.shutdown,
    projectViewport: context.projectViewport,
    configureTestRun: context.configureTestRun,
    restoreState: context.restoreState,
    testTransferState: context.testTransferState,
    testAudioPlaybackState: context.testAudioPlaybackState,
    testAudioProviderState: context.testAudioProviderState,
    liveMemoryCounters: context.liveMemoryCounters,
  };
}

type RuntimeStoreProjectionShape = ReturnType<typeof projectRuntimeStore>;
type RuntimeStoreProjection<T> = {
  [Key in keyof RuntimeStoreProjectionShape]: Key extends keyof T
    ? T[Key]
    : RuntimeStoreProjectionShape[Key];
} & RuntimeStoreProjectionExtras;

export function createRuntimeStoreProjection<T extends Record<string, any>>(
  context: T,
): RuntimeStoreProjection<T> {
  return projectRuntimeStore(context) as RuntimeStoreProjection<T>;
}
